FROM golang:1.13-alpine AS builder

ENV APP_DIR /go/src/github.com/isfonzar/slack-grand-race

COPY . ${APP_DIR}
WORKDIR ${APP_DIR}

RUN apk update && apk add make git alpine-sdk

ENV GO111MODULE off

RUN go get -u -v github.com/githubnemo/CompileDaemon

CMD CompileDaemon -build="make build" -command="out/sgr"
